// Generated by Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import CoreImage;
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
@import AVFoundation;
@import CoreMedia;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface CIFilter (SWIFT_EXTENSION(imglyKit))
@property (nonatomic, copy) NSString * __nullable imgly_displayName;
@end

enum IMGLYFilterType : NSInteger;

SWIFT_PROTOCOL("_TtP8imglyKit23IMGLYFilterTypeProtocol_")
@protocol IMGLYFilterTypeProtocol
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class CIImage;
@class NSNumber;
@class NSCoder;


/// A base clase for all response filters. Response filters use a look-up-table to
/// map colors around, and create cool effects. These tables are handed over as image
/// that contains serveral combination of r, g, and b values. Tools like photoshop can be used
/// to create filters, using the identity-image and apply the desired operations onto it.
/// Afterwards the so filtered image may be used as response map, as it represents the response the
/// filter should have.
/// In order to use the filter, the response-image is tranfered into a color-cube-map, that then
/// can be used as input for a 'CIColorCube' filter, provided by core-image.
SWIFT_CLASS("_TtC8imglyKit19IMGLYResponseFilter")
@interface IMGLYResponseFilter : CIFilter <IMGLYFilterTypeProtocol>

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;
@property (nonatomic) NSNumber * __nonnull inputIntensity;
@property (nonatomic, readonly, copy) NSString * __nonnull responseName;

/// Returns the according filter type of the response filter.
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
@end


SWIFT_CLASS("_TtC8imglyKit14IMGLYA15Filter")
@interface IMGLYA15Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYAD1920Filter")
@interface IMGLYAD1920Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYActionButton")
@interface IMGLYActionButton
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYAncientFilter")
@interface IMGLYAncientFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class CAAnimation;

SWIFT_CLASS("_TtC8imglyKit22IMGLYAnimationDelegate")
@interface IMGLYAnimationDelegate : NSObject
@property (nonatomic, readonly, copy) void (^ __nonnull block)(BOOL);
- (void)animationDidStop:(CAAnimation * __null_unspecified)anim finished:(BOOL)flag;
@end


SWIFT_CLASS("_TtC8imglyKit13IMGLYBWFilter")
@interface IMGLYBWFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit23IMGLYBleachedBlueFilter")
@interface IMGLYBleachedBlueFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYBleachedFilter")
@interface IMGLYBleachedFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit23IMGLYBlissfulBlueFilter")
@interface IMGLYBlissfulBlueFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit22IMGLYBlueShadowsFilter")
@interface IMGLYBlueShadowsFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYBluesFilter")
@interface IMGLYBluesFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class UIBezierPath;
@class UIGestureRecognizer;
@class UIPanGestureRecognizer;
@class UIPinchGestureRecognizer;

SWIFT_CLASS("_TtC8imglyKit20IMGLYBoxGradientView")
@interface IMGLYBoxGradientView : UIView
@property (nonatomic) CGPoint centerPoint;
@property (nonatomic) CGPoint controllPoint1;
@property (nonatomic) CGPoint controllPoint2;
@property (nonatomic, readonly) CGPoint normalizedControlPoint1;
@property (nonatomic, readonly) CGPoint normalizedControlPoint2;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)commonInit;
- (void)configureControlPoints;
- (void)configureCrossImageView;
- (void)configurePanGestureRecognizer;
- (void)configurePinchGestureRecognizer;
- (CGFloat)diagonalLengthOfFrame;
- (CGPoint)normalizedOrtogonalVector;
- (CGFloat)distanceBetweenControlPoints;
- (void)addLineForControlPoint1ToPath:(UIBezierPath * __nonnull)path;
- (void)addLineForControlPoint2ToPath:(UIBezierPath * __nonnull)path;
- (void)drawRect:(CGRect)rect;
- (void)calculateCenterPointFromOtherControlPoints;
- (void)informDeletageAboutRecognizerStatesWithRecognizer:(UIGestureRecognizer * __nonnull)recognizer;
- (void)handlePanGesture:(UIPanGestureRecognizer * __nonnull)recognizer;
- (void)handlePinchGesture:(UIPinchGestureRecognizer * __nonnull)recognizer;
- (BOOL)isPoint:(CGPoint)point inRect:(CGRect)rect;
- (void)layoutSubviews;
- (void)layoutCrosshair;
- (void)centerGUIElements;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYBreezeFilter")
@interface IMGLYBreezeFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class UIImage;
@class IMGLYZoomingImageView;
@class UIBarButtonItem;
@class NSBundle;

SWIFT_CLASS("_TtC8imglyKit25IMGLYEditorViewController")
@interface IMGLYEditorViewController : UIViewController
@property (nonatomic) BOOL shouldShowActivityIndicator;
@property (nonatomic) BOOL updating;
@property (nonatomic) UIImage * __nullable lowResolutionImage;
@property (nonatomic, readonly) IMGLYZoomingImageView * __nonnull previewImageView;
@property (nonatomic, readonly) UIView * __nonnull bottomContainerView;
- (void)viewDidLoad;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) BOOL enableZoomingInPreviewImage;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class IMGLYFixedFilterStack;

SWIFT_CLASS("_TtC8imglyKit28IMGLYSubEditorViewController")
@interface IMGLYSubEditorViewController : IMGLYEditorViewController
@property (nonatomic, readonly) IMGLYFixedFilterStack * __nonnull fixedFilterStack;
@property (nonatomic, copy) void (^ __nullable completionHandler)(UIImage * __nullable, IMGLYFixedFilterStack * __nonnull);
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (void)updatePreviewImageWithCompletion:(void (^ __nullable)(void))completionHandler;
@end

@class UISlider;

SWIFT_CLASS("_TtC8imglyKit31IMGLYSliderEditorViewController")
@interface IMGLYSliderEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) UISlider * __nonnull slider;
@property (nonatomic, readonly) float minimumValue;
@property (nonatomic, readonly) float maximumValue;
@property (nonatomic, readonly) float initialValue;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL enableZoomingInPreviewImage;
- (void)valueChanged:(float)value;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit35IMGLYBrightnessEditorViewController")
@interface IMGLYBrightnessEditorViewController : IMGLYSliderEditorViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) float minimumValue;
@property (nonatomic, readonly) float maximumValue;
@property (nonatomic, readonly) float initialValue;
- (void)valueChanged:(float)value;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UITapGestureRecognizer;
@class NSError;
@protocol IMGLYCameraControllerDelegate;

SWIFT_CLASS("_TtC8imglyKit21IMGLYCameraController")
@interface IMGLYCameraController : NSObject

/// The response filter that is applied to the live-feed.
@property (nonatomic) IMGLYResponseFilter * __nonnull effectFilter;
@property (nonatomic, readonly) UIView * __nonnull previewView;
@property (nonatomic, weak) id <IMGLYCameraControllerDelegate> __nullable delegate;
@property (nonatomic, readonly) UITapGestureRecognizer * __nonnull tapGestureRecognizer;
- (void)observeValueForKeyPath:(NSString * __nonnull)keyPath ofObject:(id __nonnull)object change:(NSDictionary * __nonnull)change context:(void * __null_unspecified)context;
- (void)checkDeviceAuthorizationStatus;

/// Use this property to determine if more than one camera is available. Within the SDK this property is used to determine if the toggle button is visible.
@property (nonatomic, readonly) BOOL moreThanOneCameraPresent;
- (void)toggleCameraPosition;

/// Selects the next flash-mode. The order is Auto->On->Off.
/// If the current device does not support auto-flash, this method
/// just toggles between on and off.
- (void)selectNextFlashMode;
@property (nonatomic, readonly) AVCaptureFlashMode flashMode;
- (void)disableFocusLockAnimated:(BOOL)animated;

/// Initializes the camera and has to be called before calling <code>startCamera()</code> / <code>stopCamera()</code>
- (void)setup;

/// Starts the camera preview.
- (void)startCamera;

/// Stops the camera preview.
- (void)stopCamera;

/// Check if the current device has a flash.
@property (nonatomic, readonly) BOOL flashAvailable;

/// Takes a photo and hands it over to the completion block.
///
/// If the image was taken sucessfully the error is nil.
///
/// \param completion A completion block that has an image and an error as parameters.
- (void)takePhoto:(void (^ __nonnull)(UIImage * __nullable, NSError * __nullable))completion;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface IMGLYCameraController (SWIFT_EXTENSION(imglyKit)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * __null_unspecified)captureOutput didOutputSampleBuffer:(CMSampleBufferRef __null_unspecified)sampleBuffer fromConnection:(AVCaptureConnection * __null_unspecified)connection;
@end


SWIFT_PROTOCOL("_TtP8imglyKit29IMGLYCameraControllerDelegate_")
@protocol IMGLYCameraControllerDelegate
@optional
- (void)cameraControllerDidStartCamera:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidStopCamera:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidStartStillImageCapture:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidFailAuthorization:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController didChangeToFlashMode:(AVCaptureFlashMode)flashMode;
- (void)cameraControllerDidCompleteSetup:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController willSwitchToCameraPosition:(AVCaptureDevicePosition)cameraPosition;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController didSwitchToCameraPosition:(AVCaptureDevicePosition)cameraPosition;
@end

@class UIButton;
@class IMGLYFilterSelectionController;
enum IMGLYEditorResult : NSInteger;

SWIFT_CLASS("_TtC8imglyKit25IMGLYCameraViewController")
@interface IMGLYCameraViewController : UIViewController
@property (nonatomic, readonly) UIView * __nonnull topControlsView;
@property (nonatomic, readonly) UIView * __nonnull cameraPreviewContainer;
@property (nonatomic, readonly) UIView * __nonnull bottomControlsView;
@property (nonatomic, readonly) UIButton * __nonnull flashButton;
@property (nonatomic, readonly) UIButton * __nonnull switchCameraButton;
@property (nonatomic, readonly) UIButton * __nonnull leaveCameraButton;
@property (nonatomic, readonly) UIButton * __nonnull cameraRollButton;
@property (nonatomic, readonly) UIButton * __nonnull takePhotoButton;
@property (nonatomic, readonly) UIButton * __nonnull filterSelectionButton;
@property (nonatomic, readonly) UISlider * __nonnull filterIntensitySlider;
@property (nonatomic, readonly) IMGLYFilterSelectionController * __nonnull filterSelectionController;
@property (nonatomic, readonly) IMGLYCameraController * __nullable cameraController;
@property (nonatomic, copy) void (^ __nullable completionBlock)(UIImage * __nullable);
@property (nonatomic, copy) void (^ __nullable leavecompletionBlock)(enum IMGLYEditorResult, UIImage * __nullable);
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (BOOL)shouldAutomaticallyForwardAppearanceMethods;
- (UIStatusBarStyle)preferredStatusBarStyle;
- (BOOL)prefersStatusBarHidden;
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation;
- (void)setLastImageFromRollAsPreview;
- (void)changeFlash:(UIButton * __nullable)sender;
- (void)switchCamera:(UIButton * __nullable)sender;
- (void)leaveCamera:(UIButton * __nullable)sender;
- (void)showCameraRoll:(UIButton * __nullable)sender;
- (void)takePhoto:(UIButton * __nullable)sender;
- (void)toggleFilters:(UIButton * __nullable)sender;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImagePickerController;

@interface IMGLYCameraViewController (SWIFT_EXTENSION(imglyKit)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerController:(UIImagePickerController * __nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary * __nonnull)info;
- (void)imagePickerControllerDidCancel:(UIImagePickerController * __nonnull)picker;
@end


@interface IMGLYCameraViewController (SWIFT_EXTENSION(imglyKit)) <IMGLYCameraControllerDelegate>
- (void)cameraControllerDidStartCamera:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidStopCamera:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidStartStillImageCapture:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraControllerDidFailAuthorization:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController didChangeToFlashMode:(AVCaptureFlashMode)flashMode;
- (void)cameraControllerDidCompleteSetup:(IMGLYCameraController * __nonnull)cameraController;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController willSwitchToCameraPosition:(AVCaptureDevicePosition)cameraPosition;
- (void)cameraController:(IMGLYCameraController * __nonnull)cameraController didSwitchToCameraPosition:(AVCaptureDevicePosition)cameraPosition;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYCelsiusFilter")
@interface IMGLYCelsiusFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYChestFilter")
@interface IMGLYChestFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit23IMGLYCircleGradientView")
@interface IMGLYCircleGradientView : UIView
@property (nonatomic) CGPoint centerPoint;
@property (nonatomic) CGPoint controllPoint1;
@property (nonatomic) CGPoint controllPoint2;
@property (nonatomic, readonly) CGPoint normalizedControlPoint1;
@property (nonatomic, readonly) CGPoint normalizedControlPoint2;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)commonInit;
- (void)configureControlPoints;
- (void)configureCrossImageView;
- (void)configurePanGestureRecognizer;
- (void)configurePinchGestureRecognizer;
- (CGFloat)diagonalLengthOfFrame;
- (void)drawRect:(CGRect)rect;
- (CGFloat)distanceBetweenControlPoints;
- (void)calculateCenterPointFromOtherControlPoints;
- (void)informDeletageAboutRecognizerStatesWithRecognizer:(UIGestureRecognizer * __nonnull)recognizer;
- (void)handlePanGesture:(UIPanGestureRecognizer * __nonnull)recognizer;
- (void)handlePinchGesture:(UIPinchGestureRecognizer * __nonnull)recognizer;
- (void)layoutSubviews;
- (void)layoutCrosshair;
- (void)centerGUIElements;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYClassicFilter")
@interface IMGLYClassicFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYColorButton")
@interface IMGLYColorButton : UIButton
@property (nonatomic) BOOL hasFrame;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYColorfulFilter")
@interface IMGLYColorfulFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit39IMGLYContrastBrightnessSaturationFilter")
@interface IMGLYContrastBrightnessSaturationFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;
@property (nonatomic) float contrast;
@property (nonatomic) float brightness;
@property (nonatomic) float saturation;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYContrastBrightnessSaturationFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC8imglyKit33IMGLYContrastEditorViewController")
@interface IMGLYContrastEditorViewController : IMGLYSliderEditorViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) float minimumValue;
@property (nonatomic, readonly) float maximumValue;
@property (nonatomic, readonly) float initialValue;
- (void)valueChanged:(float)value;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYCoolFilter")
@interface IMGLYCoolFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit22IMGLYCottonCandyFilter")
@interface IMGLYCottonCandyFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYCreamyFilter")
@interface IMGLYCreamyFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class IMGLYImageCaptionButton;
enum IMGLYSelectionMode : NSInteger;

SWIFT_CLASS("_TtC8imglyKit29IMGLYCropEditorViewController")
@interface IMGLYCropEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull freeRatioButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull oneToOneRatioButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull fourToThreeRatioButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull sixteenToNineRatioButton;
@property (nonatomic) enum IMGLYSelectionMode selectionMode;
@property (nonatomic) CGFloat selectionRatio;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (void)handlePan:(UIPanGestureRecognizer * __nonnull)recognizer;
- (void)handlePanOnTopLeft:(UIPanGestureRecognizer * __nonnull)recognizer;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end



/// Provides a filter to crop images.
SWIFT_CLASS("_TtC8imglyKit15IMGLYCropFilter")
@interface IMGLYCropFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;

/// A rect that describes the area that should remain after cropping. 
/// The values are relative.
@property (nonatomic) CGRect cropRect;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
@end


@interface IMGLYCropFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end

typedef SWIFT_ENUM(NSInteger, IMGLYEditorResult) {
  IMGLYEditorResultDone = 0,
  IMGLYEditorResultCancel = 1,
};



SWIFT_CLASS("_TtC8imglyKit19IMGLYEightiesFilter")
@interface IMGLYEightiesFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYElderFilter")
@interface IMGLYElderFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end



/// This class uses apples auto-enhancement filters to improve the overall
/// quality of an image. Due the way this filter is used within this SDK,
/// there is a mechanism that retains the enhanced image until its resetted
/// and a recalculation is foced. This behaviour is inactive by default, and
/// can be activated by setting 'storeEnhancedImage' to true.
SWIFT_CLASS("_TtC8imglyKit22IMGLYEnhancementFilter")
@interface IMGLYEnhancementFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;

/// If this is set to false, the original image is returned.
@property (nonatomic) BOOL enabled;

/// If this is set to true, the enhanced image is kept until reset is called.
@property (nonatomic) BOOL storeEnhancedImage;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
- (void)reset;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYEnhancementFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYEveningFilter")
@interface IMGLYEveningFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYFallFilter")
@interface IMGLYFallFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit31IMGLYFilterEditorViewController")
@interface IMGLYFilterEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYFilterSelectionController * __nonnull filterSelectionController;
@property (nonatomic, readonly) UISlider * __nonnull filterIntensitySlider;
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL enableZoomingInPreviewImage;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit30IMGLYFilterSelectionController")
@interface IMGLYFilterSelectionController : UICollectionViewController
@property (nonatomic, copy) void (^ __nullable selectedBlock)(enum IMGLYFilterType);
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;
@class NSIndexPath;

@interface IMGLYFilterSelectionController (SWIFT_EXTENSION(imglyKit)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * __nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end

@class UICollectionViewCell;

@interface IMGLYFilterSelectionController (SWIFT_EXTENSION(imglyKit)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * __nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * __nonnull)collectionView:(UICollectionView * __nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


/// All types of response-filters.
typedef SWIFT_ENUM(NSInteger, IMGLYFilterType) {
  IMGLYFilterTypeNone = 0,
  IMGLYFilterTypeK1 = 1,
  IMGLYFilterTypeK2 = 2,
  IMGLYFilterTypeK6 = 3,
  IMGLYFilterTypeKDynamic = 4,
  IMGLYFilterTypeFridge = 5,
  IMGLYFilterTypeBreeze = 6,
  IMGLYFilterTypeOrchid = 7,
  IMGLYFilterTypeChest = 8,
  IMGLYFilterTypeFront = 9,
  IMGLYFilterTypeFixie = 10,
  IMGLYFilterTypeX400 = 11,
  IMGLYFilterTypeBW = 12,
  IMGLYFilterTypeAD1920 = 13,
  IMGLYFilterTypeLenin = 14,
  IMGLYFilterTypeQuozi = 15,
  IMGLYFilterTypePola669 = 16,
  IMGLYFilterTypePolaSX = 17,
  IMGLYFilterTypeFood = 18,
  IMGLYFilterTypeGlam = 19,
  IMGLYFilterTypeCelsius = 20,
  IMGLYFilterTypeTexas = 21,
  IMGLYFilterTypeLomo = 22,
  IMGLYFilterTypeGoblin = 23,
  IMGLYFilterTypeSin = 24,
  IMGLYFilterTypeMellow = 25,
  IMGLYFilterTypeSunny = 26,
  IMGLYFilterTypeA15 = 27,
  IMGLYFilterTypeSoft = 28,
  IMGLYFilterTypeBlues = 29,
  IMGLYFilterTypeElder = 30,
  IMGLYFilterTypeSunset = 31,
  IMGLYFilterTypeEvening = 32,
  IMGLYFilterTypeSteel = 33,
  IMGLYFilterTypeSeventies = 34,
  IMGLYFilterTypeHighContrast = 35,
  IMGLYFilterTypeBlueShadows = 36,
  IMGLYFilterTypeHighcarb = 37,
  IMGLYFilterTypeEighties = 38,
  IMGLYFilterTypeColorful = 39,
  IMGLYFilterTypeLomo100 = 40,
  IMGLYFilterTypePro400 = 41,
  IMGLYFilterTypeTwilight = 42,
  IMGLYFilterTypeCottonCandy = 43,
  IMGLYFilterTypeMono3200 = 44,
  IMGLYFilterTypeBlissfulBlue = 45,
  IMGLYFilterTypePale = 46,
  IMGLYFilterTypeSettled = 47,
  IMGLYFilterTypeCool = 48,
  IMGLYFilterTypeLitho = 49,
  IMGLYFilterTypePrelude = 50,
  IMGLYFilterTypeNepal = 51,
  IMGLYFilterTypeAncient = 52,
  IMGLYFilterTypePitched = 53,
  IMGLYFilterTypeLucid = 54,
  IMGLYFilterTypeCreamy = 55,
  IMGLYFilterTypeKeen = 56,
  IMGLYFilterTypeTender = 57,
  IMGLYFilterTypeBleached = 58,
  IMGLYFilterTypeBleachedBlue = 59,
  IMGLYFilterTypeFall = 60,
  IMGLYFilterTypeWinter = 61,
  IMGLYFilterTypeSepiaHigh = 62,
  IMGLYFilterTypeSummer = 63,
  IMGLYFilterTypeClassic = 64,
  IMGLYFilterTypeNoGreen = 65,
  IMGLYFilterTypeNeat = 66,
  IMGLYFilterTypePlate = 67,
};


@class IMGLYOrientationCropFilter;
@class IMGLYTiltshiftFilter;
@class IMGLYTextFilter;


/// <ul><li><p>This class represents the filterstack that is used when using the UI.</p></li><li><p>It represents a chain of filters that will be applied to the taken image.</p></li><li><p>That way we make sure the order of filters stays the same, and we don't need to take</p></li><li><p>care about creating the single filters.</p></li></ul>
SWIFT_CLASS("_TtC8imglyKit21IMGLYFixedFilterStack")
@interface IMGLYFixedFilterStack : NSObject
@property (nonatomic) IMGLYEnhancementFilter * __nonnull enhancementFilter;
@property (nonatomic) IMGLYOrientationCropFilter * __nonnull orientationCropFilter;
@property (nonatomic) IMGLYResponseFilter * __nonnull effectFilter;
@property (nonatomic) IMGLYContrastBrightnessSaturationFilter * __nonnull brightnessFilter;
@property (nonatomic) IMGLYTiltshiftFilter * __nonnull tiltShiftFilter;
@property (nonatomic) IMGLYTextFilter * __nonnull textFilter;
@property (nonatomic, copy) NSArray * __nonnull stickerFilters;
@property (nonatomic, readonly, copy) NSArray * __nonnull activeFilters;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYFixedFilterStack (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYFixieFilter")
@interface IMGLYFixieFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit30IMGLYFocusEditorViewController")
@interface IMGLYFocusEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull offButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull linearButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull radialButton;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYFocusEditorViewController (SWIFT_EXTENSION(imglyKit))
- (void)userInteractionStarted;
- (void)userInteractionEnded;
- (void)controlPointChanged;
@end


SWIFT_CLASS("_TtC8imglyKit21IMGLYFontSelectorView")
@interface IMGLYFontSelectorView : UIScrollView
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYFoodFilter")
@interface IMGLYFoodFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYFridgeFilter")
@interface IMGLYFridgeFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYFrontFilter")
@interface IMGLYFrontFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYGlamFilter")
@interface IMGLYGlamFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYGoblinFilter")
@interface IMGLYGoblinFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit23IMGLYHighContrastFilter")
@interface IMGLYHighContrastFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYHighcarbFilter")
@interface IMGLYHighcarbFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

@class UILabel;
@class UIImageView;

SWIFT_CLASS("_TtC8imglyKit23IMGLYImageCaptionButton")
@interface IMGLYImageCaptionButton : UIControl
@property (nonatomic, readonly) UILabel * __nonnull textLabel;
@property (nonatomic, readonly) UIImageView * __nonnull imageView;
@property (nonatomic, getter=isHighlighted, setter=setHighlighted:) BOOL highlighted;
@property (nonatomic, getter=isSelected, setter=setSelected:) BOOL selected;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGSize)sizeThatFits:(CGSize)size;
+ (BOOL)requiresConstraintBasedLayout;
@end

@class IMGLYStickerFilter;


/// A singleton that is out to create objects. It is used within the SDK to 
/// create filters, views, viewcontrollers and such.
SWIFT_CLASS("_TtC8imglyKit20IMGLYInstanceFactory")
@interface IMGLYInstanceFactory

/// Creates a response filter with the specified type.
///
/// \param type The type of the filter that should be created.
///
/// \returns A CIFilter object that realizes the desired filter.
+ (IMGLYResponseFilter * __nonnull)effectFilterWithType:(enum IMGLYFilterType)type;

/// Creates a text filter.
///
/// \returns A text filter
+ (IMGLYTextFilter * __nonnull)textFilter;

/// Creates a sticker filter.
///
/// \returns A sticker filter
+ (IMGLYStickerFilter * __nonnull)stickerFilter;

/// Creates a crop filter.
///
/// \returns A crop filter
+ (IMGLYOrientationCropFilter * __nonnull)orientationCropFilter;

/// Creates a tiltshift filter.
///
/// \returns A tiltshift filter.
+ (IMGLYTiltshiftFilter * __nonnull)tiltShiftFilter;

/// Creates a color-adjustment filter.
///
/// \returns A color-adjustment filter.
+ (IMGLYContrastBrightnessSaturationFilter * __nonnull)colorAdjustmentFilter;

/// Creates an enhancement filter.
///
/// \returns A enhancement filter.
+ (IMGLYEnhancementFilter * __nonnull)enhancementFilter;

/// Returns a list that determins what fonts will be available within
/// the text-dialog.
///
/// \returns An array of fontnames.
+ (NSArray * __nonnull)availableFontsList;
@end

enum IMGLYMainMenuButtonType : NSInteger;
@class IMGLYStickersEditorViewController;
@class IMGLYOrientationEditorViewController;
@class IMGLYSaturationEditorViewController;
@class IMGLYTextEditorViewController;

@interface IMGLYInstanceFactory (SWIFT_EXTENSION(imglyKit))

/// Return the viewcontroller according to the button-type.
/// This is used by the main menu.
///
/// \param type The type of the button pressed.
///
/// \returns A viewcontroller according to the button-type.
+ (IMGLYSubEditorViewController * __nullable)viewControllerForButtonType:(enum IMGLYMainMenuButtonType)type withFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYFilterEditorViewController * __nonnull)filterEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYStickersEditorViewController * __nonnull)stickersEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYOrientationEditorViewController * __nonnull)orientationEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYFocusEditorViewController * __nonnull)focusEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYCropEditorViewController * __nonnull)cropEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYBrightnessEditorViewController * __nonnull)brightnessEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYContrastEditorViewController * __nonnull)contrastEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYSaturationEditorViewController * __nonnull)saturationEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYTextEditorViewController * __nonnull)textEditorViewControllerWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack;
+ (IMGLYCircleGradientView * __nonnull)circleGradientView;
+ (IMGLYBoxGradientView * __nonnull)boxGradientView;
@end


SWIFT_CLASS("_TtC8imglyKit13IMGLYK1Filter")
@interface IMGLYK1Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit13IMGLYK2Filter")
@interface IMGLYK2Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit13IMGLYK6Filter")
@interface IMGLYK6Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYKDynamicFilter")
@interface IMGLYKDynamicFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYKeenFilter")
@interface IMGLYKeenFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYLeninFilter")
@interface IMGLYLeninFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYLithoFilter")
@interface IMGLYLithoFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYLomo100Filter")
@interface IMGLYLomo100Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYLomoFilter")
@interface IMGLYLomoFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYLucidFilter")
@interface IMGLYLucidFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit29IMGLYMainEditorViewController")
@interface IMGLYMainEditorViewController : IMGLYEditorViewController
@property (nonatomic, copy) NSArray * __nonnull actionButtons;
@property (nonatomic, copy) void (^ __nullable completionBlock)(enum IMGLYEditorResult, UIImage * __nullable);
@property (nonatomic) enum IMGLYFilterType initialFilterType;
@property (nonatomic) NSNumber * __nonnull initialFilterIntensity;
@property (nonatomic, readonly) IMGLYFixedFilterStack * __nonnull fixedFilterStack;
@property (nonatomic) UIImage * __nullable highResolutionImage;
- (void)viewDidLoad;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
@property (nonatomic, readonly) BOOL enableZoomingInPreviewImage;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UINavigationController;
@protocol UIViewControllerAnimatedTransitioning;

@interface IMGLYMainEditorViewController (SWIFT_EXTENSION(imglyKit)) <UINavigationControllerDelegate>
- (id <UIViewControllerAnimatedTransitioning> __nullable)navigationController:(UINavigationController * __nonnull)navigationController animationControllerForOperation:(UINavigationControllerOperation)operation fromViewController:(UIViewController * __nonnull)fromVC toViewController:(UIViewController * __nonnull)toVC;
@end


@interface IMGLYMainEditorViewController (SWIFT_EXTENSION(imglyKit)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * __nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


@interface IMGLYMainEditorViewController (SWIFT_EXTENSION(imglyKit)) <UICollectionViewDataSource>
- (NSInteger)collectionView:(UICollectionView * __nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * __nonnull)collectionView:(UICollectionView * __nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end

typedef SWIFT_ENUM(NSInteger, IMGLYMainMenuButtonType) {
  IMGLYMainMenuButtonTypeMagic = 0,
  IMGLYMainMenuButtonTypeFilter = 1,
  IMGLYMainMenuButtonTypeStickers = 2,
  IMGLYMainMenuButtonTypeOrientation = 3,
  IMGLYMainMenuButtonTypeFocus = 4,
  IMGLYMainMenuButtonTypeCrop = 5,
  IMGLYMainMenuButtonTypeBrightness = 6,
  IMGLYMainMenuButtonTypeContrast = 7,
  IMGLYMainMenuButtonTypeSaturation = 8,
  IMGLYMainMenuButtonTypeNoise = 9,
  IMGLYMainMenuButtonTypeText = 10,
  IMGLYMainMenuButtonTypeReset = 11,
};


SWIFT_CLASS("_TtC8imglyKit17IMGLYMellowFilter")
@interface IMGLYMellowFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYMono3200Filter")
@interface IMGLYMono3200Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit25IMGLYNavigationController")
@interface IMGLYNavigationController : UINavigationController
- (BOOL)shouldAutorotate;
- (UIInterfaceOrientation)preferredInterfaceOrientationForPresentation;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNavigationBarClass:(Class __nullable)navigationBarClass toolbarClass:(Class __nullable)toolbarClass OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithRootViewController:(UIViewController * __nonnull)rootViewController OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithNibName:(NSString * __nullable)nibNameOrNil bundle:(NSBundle * __nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYNeatFilter")
@interface IMGLYNeatFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYNepalFilter")
@interface IMGLYNepalFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYNoGreenFilter")
@interface IMGLYNoGreenFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end



/// <ul><li><p>A filter that does nothing. It is used within the fixed-filterstack.</p></li></ul>
SWIFT_CLASS("_TtC8imglyKit15IMGLYNoneFilter")
@interface IMGLYNoneFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYOrchidFilter")
@interface IMGLYOrchidFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end

enum IMGLYRotationAngle : NSInteger;


/// <blockquote><p>Performes a rotation/flip operation and then a crop.</p></blockquote>
/// Note that the result of the rotate/flip operation id transfered  to a temp CGImage.
/// This is needed since otherwise the resulting CIImage has no no size due the lack of inforamtion within
/// the CIImage.
SWIFT_CLASS("_TtC8imglyKit26IMGLYOrientationCropFilter")
@interface IMGLYOrientationCropFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;
@property (nonatomic) CGRect cropRect;
@property (nonatomic) enum IMGLYRotationAngle rotationAngle;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;

/// Sets internal flags so that the filtered image will be rotated counter-clock-wise around 90 degrees.
- (void)rotateLeft;

/// Sets internal flags so that the filtered image will be rotated clock-wise around 90 degrees.
- (void)rotateRight;

/// Sets internal flags so that the filtered image will be rotated flipped along the horizontal axis.
- (void)flipHorizontal;

/// Sets internal flags so that the filtered image will be rotated flipped along the vertical axis.
- (void)flipVertical;
@end


@interface IMGLYOrientationCropFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC8imglyKit36IMGLYOrientationEditorViewController")
@interface IMGLYOrientationEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull rotateLeftButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull rotateRightButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull flipHorizontallyButton;
@property (nonatomic, readonly) IMGLYImageCaptionButton * __nonnull flipVerticallyButton;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
@property (nonatomic, readonly) BOOL enableZoomingInPreviewImage;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYPaleFilter")
@interface IMGLYPaleFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit19IMGLYPhotoProcessor")
@interface IMGLYPhotoProcessor
+ (CIImage * __nullable)processWithCIImage:(CIImage * __nonnull)image filters:(NSArray * __nonnull)filters;
+ (UIImage * __nullable)processWithUIImage:(UIImage * __nonnull)image filters:(NSArray * __nonnull)filters;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYPitchedFilter")
@interface IMGLYPitchedFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYPlateFilter")
@interface IMGLYPlateFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYPola669Filter")
@interface IMGLYPola669Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYPolaSXFilter")
@interface IMGLYPolaSXFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYPreludeFilter")
@interface IMGLYPreludeFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYPro400Filter")
@interface IMGLYPro400Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYQuoziFilter")
@interface IMGLYQuoziFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end



@interface IMGLYResponseFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


/// Represents the angle an image should be rotated by.
typedef SWIFT_ENUM(NSInteger, IMGLYRotationAngle) {
  IMGLYRotationAngle_0 = 0,
  IMGLYRotationAngle_90 = 1,
  IMGLYRotationAngle_180 = 2,
  IMGLYRotationAngle_270 = 3,
};


SWIFT_CLASS("_TtC8imglyKit35IMGLYSaturationEditorViewController")
@interface IMGLYSaturationEditorViewController : IMGLYSliderEditorViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) float minimumValue;
@property (nonatomic, readonly) float maximumValue;
@property (nonatomic, readonly) float initialValue;
- (void)valueChanged:(float)value;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, IMGLYSelectionMode) {
  IMGLYSelectionModeFree = 0,
  IMGLYSelectionModeOneToOne = 1,
  IMGLYSelectionModeFourToThree = 2,
  IMGLYSelectionModeSixteenToNine = 3,
};


SWIFT_CLASS("_TtC8imglyKit20IMGLYSepiaHighFilter")
@interface IMGLYSepiaHighFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYSettledFilter")
@interface IMGLYSettledFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit20IMGLYSeventiesFilter")
@interface IMGLYSeventiesFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit14IMGLYSinFilter")
@interface IMGLYSinFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end



SWIFT_CLASS("_TtC8imglyKit15IMGLYSoftFilter")
@interface IMGLYSoftFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYSteelFilter")
@interface IMGLYSteelFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit12IMGLYSticker")
@interface IMGLYSticker : NSObject
@property (nonatomic, readonly) UIImage * __nonnull image;
@property (nonatomic, readonly) UIImage * __nullable thumbnail;
@end


SWIFT_CLASS("_TtC8imglyKit18IMGLYStickerFilter")
@interface IMGLYStickerFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;
@property (nonatomic) UIImage * __nullable sticker;

/// The transform to apply to the sticker
@property (nonatomic) CGAffineTransform transform;

/// The relative center of the sticker within the image.
@property (nonatomic) CGPoint center;

/// The relative size of the sticker within the image.
@property (nonatomic) CGSize size;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
@end


@interface IMGLYStickerFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end


SWIFT_CLASS("_TtC8imglyKit23IMGLYStickersDataSource")
@interface IMGLYStickersDataSource : NSObject
@property (nonatomic, readonly, copy) NSArray * __nonnull stickers;
- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView * __nonnull)collectionView;
- (NSInteger)collectionView:(UICollectionView * __nonnull)collectionView numberOfItemsInSection:(NSInteger)section;
- (UICollectionViewCell * __nonnull)collectionView:(UICollectionView * __nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8imglyKit33IMGLYStickersEditorViewController")
@interface IMGLYStickersEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYStickersDataSource * __nonnull stickersDataSource;
@property (nonatomic, readonly) UIView * __nonnull stickersClipView;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYStickersEditorViewController (SWIFT_EXTENSION(imglyKit)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * __nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * __nonnull)otherGestureRecognizer;
@end


@interface IMGLYStickersEditorViewController (SWIFT_EXTENSION(imglyKit)) <UICollectionViewDelegate>
- (void)collectionView:(UICollectionView * __nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * __nonnull)indexPath;
@end



SWIFT_CLASS("_TtC8imglyKit17IMGLYSummerFilter")
@interface IMGLYSummerFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYSunnyFilter")
@interface IMGLYSunnyFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYSunsetFilter")
@interface IMGLYSunsetFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYTenderFilter")
@interface IMGLYTenderFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit16IMGLYTexasFilter")
@interface IMGLYTexasFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit26IMGLYTextColorSelectorView")
@interface IMGLYTextColorSelectorView : UIScrollView
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end

@class UITextField;
@class UIVisualEffectView;

SWIFT_CLASS("_TtC8imglyKit29IMGLYTextEditorViewController")
@interface IMGLYTextEditorViewController : IMGLYSubEditorViewController
@property (nonatomic, readonly) IMGLYTextColorSelectorView * __nonnull textColorSelectorView;
@property (nonatomic, readonly) UIView * __nonnull textClipView;
@property (nonatomic, readonly) UITextField * __nonnull textField;
@property (nonatomic, readonly) UILabel * __nonnull textLabel;
@property (nonatomic, readonly) UIVisualEffectView * __nonnull fontSelectorContainerView;
@property (nonatomic, readonly) IMGLYFontSelectorView * __nonnull fontSelectorView;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)tappedDone:(UIBarButtonItem * __nullable)sender;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFixedFilterStack:(IMGLYFixedFilterStack * __nonnull)fixedFilterStack OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYTextEditorViewController (SWIFT_EXTENSION(imglyKit))
- (void)fontSelectorView:(IMGLYFontSelectorView * __nonnull)fontSelectorView didSelectFontWithName:(NSString * __nonnull)fontName;
@end

@class UIColor;

@interface IMGLYTextEditorViewController (SWIFT_EXTENSION(imglyKit))
- (void)textColorSelectorView:(IMGLYTextColorSelectorView * __nonnull)selectorView didSelectColor:(UIColor * __nonnull)color;
@end


@interface IMGLYTextEditorViewController (SWIFT_EXTENSION(imglyKit)) <UITextFieldDelegate>
- (BOOL)textFieldShouldBeginEditing:(UITextField * __nonnull)textField;
- (BOOL)textFieldShouldEndEditing:(UITextField * __nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * __nonnull)textField;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYTextFilter")
@interface IMGLYTextFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;

/// The text that should be rendered.
@property (nonatomic, copy) NSString * __nonnull text;

/// The name of the used font.
@property (nonatomic, copy) NSString * __nonnull fontName;

/// This factor determins the font-size. Its a relative value that is multiplied with the image height
/// during the process.
@property (nonatomic) CGFloat fontScaleFactor;

/// The relative frame of the text within the image.
@property (nonatomic) CGRect frame;
@property (nonatomic) UIColor * __nonnull color;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
@end


@interface IMGLYTextFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end

enum IMGLYTiltshiftType : NSInteger;


/// This class realizes a tilt-shit filter effect. That means that a part a of the image is blurred.
/// The non-blurry part of the image can be defined either by a circle or a box, defined by the tiltShiftType variable.
/// Both, circle and box, are described by the controlPoint1 and controlPoint2 variable, that mark 
/// either two oppesite points on the radius of the circle, or two points on oppesite sides of the box.
SWIFT_CLASS("_TtC8imglyKit20IMGLYTiltshiftFilter")
@interface IMGLYTiltshiftFilter : CIFilter

/// A CIImage object that serves as input for the filter.
@property (nonatomic) CIImage * __nullable inputImage;

/// One of the two points, marking the dimension and direction of the box or circle.
@property (nonatomic) CGPoint controlPoint1;

/// One of the two points, marking the dimension and direction of the box or circle.
@property (nonatomic) CGPoint controlPoint2;

/// Defines the mode the filter operates in. Possible values are Box, Circle, and Off.
@property (nonatomic) enum IMGLYTiltshiftType tiltShiftType;

/// The radius that is set to the gaussian filter during the whole process. Default is 4.
@property (nonatomic) CGFloat blurRadius;

/// Returns a CIImage object that encapsulates the operations configured in the filter. (read-only)
@property (nonatomic, readonly, getter=outputImage) CIImage * __null_unspecified outputImage;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface IMGLYTiltshiftFilter (SWIFT_EXTENSION(imglyKit)) <NSCopying>
- (id __nonnull)copyWithZone:(NSZone * __null_unspecified)zone;
@end

typedef SWIFT_ENUM(NSInteger, IMGLYTiltshiftType) {
  IMGLYTiltshiftTypeOff = 0,
  IMGLYTiltshiftTypeBox = 1,
  IMGLYTiltshiftTypeCircle = 2,
};


SWIFT_CLASS("_TtC8imglyKit19IMGLYTwilightFilter")
@interface IMGLYTwilightFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit17IMGLYWinterFilter")
@interface IMGLYWinterFilter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit15IMGLYX400Filter")
@interface IMGLYX400Filter : IMGLYResponseFilter
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly) enum IMGLYFilterType filterType;
@end


SWIFT_CLASS("_TtC8imglyKit21IMGLYZoomingImageView")
@interface IMGLYZoomingImageView : UIScrollView
@property (nonatomic) UIImage * __nullable image;
@property (nonatomic) UITapGestureRecognizer * __nonnull doubleTapGestureRecognizer;
@property (nonatomic, readonly) CGRect visibleImageFrame;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


@interface IMGLYZoomingImageView (SWIFT_EXTENSION(imglyKit)) <UIScrollViewDelegate>
- (UIView * __nullable)viewForZoomingInScrollView:(UIScrollView * __nonnull)scrollView;
- (void)scrollViewDidZoom:(UIScrollView * __nonnull)scrollView;
@end


@interface NSTimer (SWIFT_EXTENSION(imglyKit))
@end


@interface UIImage (SWIFT_EXTENSION(imglyKit))

/// Returns a copy of the image, taking into account its orientation
@property (nonatomic, readonly) UIImage * __nonnull imgly_normalizedImage;

/// Returns a rescaled copy of the image, taking into account its orientation
///
/// <dl><dt>discussion</dt><dd><p>The image will be scaled disproportionately if necessary to fit the bounds specified by the parameter.</p></dd></dl>
/// \param size The size of the rescaled image.
///
/// \returns The rescaled image.
- (UIImage * __nonnull)imgly_normalizedImageOfSize:(CGSize)size;
@end

#pragma clang diagnostic pop
